server:
  port: 8083
  servlet:
    context-path: /api/

spring:
  application:
    name: notification-service
  mail:
    port: 587
    protocol: smtp
    host: smtp.gmail.com
    username: alext0408@gmail.com
    password: ennyuzydpnpovync
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        ssl:
          trust: smtp.gmail.com

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/